export const MUTATIONS = {
    INCREMENT: 'INCREMENT',
    SET_COUNT: 'SET_COUNT',
    SET_GAME_WIDTH: 'SET_GAME_WIDTH',
    SET_GAME_HEIGHT: 'SET_GAME_HEIGHT',
    SET_GAME_SIZE: 'SET_GAME_SIZE',
    SET_GAME_BOARD: 'SET_GAME_BOARD',
    SET_GAME_WIN: 'SET_GAME_WIN',
    RESET_GAME: 'RESET_GAME'
}
