import { EnemyType } from '@/shared/types';
import { Mutations } from '@/store/types';

export const MUTATIONS: { [K in keyof Mutations]: K } = {
  SET_MONEY: 'SET_MONEY',
  ADD_MONEY: 'ADD_MONEY',
  REDUCE_MONEY: 'REDUCE_MONEY',
  SET_IS_PLAYING: 'SET_IS_PLAYING',
  SET_GAME_OVER: 'SET_GAME_OVER',
  SET_GAME_RESULT: 'SET_GAME_RESULT',
  SET_LEVEL_ID: 'SET_LEVEL_ID',
  SET_ZONE_SIZE: 'SET_ZONE_SIZE',
  SET_BUILD_ZONES: 'SET_BUILD_ZONES',
  SET_PATH: 'SET_PATH',
  SET_PATH_PIXEL: 'SET_PATH_PIXEL',
  SET_TOWERS: 'SET_TOWERS',
  SET_ENEMIES: 'SET_ENEMIES',
  SET_SELECTED_ENEMY_INDEX: 'SET_SELECTED_ENEMY_INDEX',
  SET_SPAWN_CONFIG: 'SET_SPAWN_CONFIG',
  SET_SPAWN_STATE: 'SET_SPAWN_STATE',
  RESET_LEVEL_STATE: 'RESET_LEVEL_STATE',
};

export const TOWER_BASE_COST = 50;

export const SELECT_THRESHOLD_PX = 20;

export const REWARDS_BY_TYPE: Record<EnemyType, number> = {
  common: 25,
  medium: 50,
  hard: 100,
};
