import { EnemyType } from '@/shared/types';
import { Mutations } from '@/store/types';

export const MUTATIONS: { [K in keyof Mutations]: K } = {
  SET_MONEY: 'SET_MONEY',
  ADD_MONEY: 'ADD_MONEY',
  REDUCE_MONEY: 'REDUCE_MONEY',
  SET_IS_PLAYING: 'SET_IS_PLAYING',
  SET_GAME_OVER: 'SET_GAME_OVER',
  SET_GAME_RESULT: 'SET_GAME_RESULT',
  SET_LEVEL_ID: 'SET_LEVEL_ID',
  SET_ZONE_SIZE: 'SET_ZONE_SIZE',
  SET_BUILD_ZONES: 'SET_BUILD_ZONES',
  SET_PATH: 'SET_PATH',
  SET_PATH_PIXEL: 'SET_PATH_PIXEL',
  SET_REVERSE_PATH: 'SET_REVERSE_PATH',
  SET_REVERSE_PATH_PIXEL: 'SET_REVERSE_PATH_PIXEL',
  SET_TOWERS: 'SET_TOWERS',
  SET_ENEMIES: 'SET_ENEMIES',
  SET_SHOOTER_ENEMIES: 'SET_SHOOTER_ENEMIES',
  SET_ALLIES: 'SET_ALLIES',
  SET_BARRICADES: 'SET_BARRICADES',
  SET_ARTILLERY_STRIKES: 'SET_ARTILLERY_STRIKES',
  SET_SELECTED_ENEMY_INDEX: 'SET_SELECTED_ENEMY_INDEX',
  SET_SPAWN_CONFIG: 'SET_SPAWN_CONFIG',
  SET_SPAWN_STATE: 'SET_SPAWN_STATE',
  RESET_LEVEL_STATE: 'RESET_LEVEL_STATE',
};

export const TOWER_BASE_COST = 50;
export const BARRICADE_WOODEN_COST = 30;
export const BARRICADE_STONE_COST = 60;
export const BARRICADE_METAL_COST = 100;
export const ARTILLERY_STRIKE_COST = 80;
export const ALLY_SOLDIER_COST = 40;
export const ALLY_HEAVY_SOLDIER_COST = 70;

export const BARRICADE_COSTS = {
  wooden: BARRICADE_WOODEN_COST,
  stone: BARRICADE_STONE_COST,
  metal: BARRICADE_METAL_COST,
};

export const SELECT_THRESHOLD_PX = 20;

export const REWARDS_BY_TYPE: Record<EnemyType, number> = {
  common: 25,
  medium: 50,
  hard: 100,
};
