export const MUTATIONS = {
    INCREMENT: 'INCREMENT',
    SET_COUNT: 'SET_COUNT',
    SET_GAME_WIDTH: 'SET_GAME_WIDTH',
    SET_GAME_HEIGHT: 'SET_GAME_HEIGHT',
    SET_GAME_SIZE: 'SET_GAME_SIZE',
    SET_GAME_BOARD: 'SET_GAME_BOARD',
    SET_GAME_WIN: 'SET_GAME_WIN',
    RESET_GAME: 'RESET_GAME',
    SET_BLOCKED_MODE: 'SET_BLOCKED_MODE',
    SET_BLOCKED_CELLS: 'SET_BLOCKED_CELLS',
    SET_SPECIAL_MOVE_AVAILABLE: 'SET_SPECIAL_MOVE_AVAILABLE',
    SET_GAME_TIME: 'SET_GAME_TIME',
    SET_IS_PLAYING: 'SET_IS_PLAYING',
    SET_RECORDS: 'SET_RECORDS'
}
