services:
  web:
    build:
      context: ./vue
      dockerfile: Dockerfile.runtime
    image: vue-fiit-web:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${CERTS_HOST_DIR}:/etc/nginx/certs:rw
