export const LEVELS = [
  { id: 1, isAvailable: true },
  { id: 2, isAvailable: true },
  { id: 3, isAvailable: false },
  { id: 4, isAvailable: false },
  { id: 5, isAvailable: false },
  { id: 6, isAvailable: false },
  { id: 7, isAvailable: false },
  { id: 8, isAvailable: false },
  { id: 9, isAvailable: false },
  { id: 10, isAvailable: false },
  { id: 11, isAvailable: false },
  { id: 12, isAvailable: false },
  { id: 13, isAvailable: false },
  { id: 14, isAvailable: false },
  { id: 15, isAvailable: false },
  { id: 16, isAvailable: false },
  { id: 17, isAvailable: false },
  { id: 18, isAvailable: false },
  { id: 19, isAvailable: false },
  { id: 20, isAvailable: false },
];
