export const MUTATIONS = {
    SET_SHAPE: 'SET_SHAPE',
    ADD_OBJECT: 'ADD_OBJECT',
    REMOVE_OBJECT: 'REMOVE_OBJECT',
    SET_MODE: 'SET_MODE',
    SET_DRAGGING: 'SET_DRAGGING',
    SET_PREVIEW_ORIGIN: 'SET_PREVIEW_ORIGIN',
    SET_GRID_SIZE: 'SET_GRID_SIZE',
    SET_PANNING: 'SET_PANNING',
    SET_OFFSET: 'SET_OFFSET',
    MOVE_OFFSET: 'MOVE_OFFSET',
    SET_SCALE: 'SET_SCALE',
    DECREASE_BALANCE: 'DECREASE_BALANCE',
    INCREASE_BALANCE: 'INCREASE_BALANCE',
    ADD_VISITOR: 'ADD_VISITOR'
}