export const COSTS = {
  TOWER: 100,
  ALLY: 80,
  BARRICADE: 40,
  ARTILLERY: 40
}

export const ATTACK = {
  ALLY_DAMAGE: 20,
  ALLY_RANGE: 80,
  ALLY_COOLDOWN: 800
}

export const MUTATIONS = {
  SET_LEVELS: 'SET_LEVELS',
  SET_LEVEL: 'SET_LEVEL',
  RESET_GAME_STATE: 'RESET_GAME_STATE',
  ADD_POINTS: 'ADD_POINTS',
  REMOVE_POINTS: 'REMOVE_POINTS',
  SET_INSUFFICIENT_FUNDS: 'SET_INSUFFICIENT_FUNDS',
  SET_PLACE_MODE: 'SET_PLACE_MODE',
  ADD_ENEMY: 'ADD_ENEMY',
  UPDATE_ENEMIES: 'UPDATE_ENEMIES',
  ADD_ALLY: 'ADD_ALLY',
  UPDATE_ALLIES: 'UPDATE_ALLIES',
  ADD_TOWER: 'ADD_TOWER',
  UPDATE_TOWERS: 'UPDATE_TOWERS',
  REMOVE_TOWER: 'REMOVE_TOWER',
  SET_TOWER_HIT: 'SET_TOWER_HIT',
  ADD_BARRICADE: 'ADD_BARRICADE',
  UPDATE_BARRICADES: 'UPDATE_BARRICADES',
  ADD_ARTILLERY_STRIKE: 'ADD_ARTILLERY_STRIKE',
  UPDATE_ARTILLERY_STRIKES: 'UPDATE_ARTILLERY_STRIKES',
  ADD_SHOT: 'ADD_SHOT',
  REMOVE_SHOT: 'REMOVE_SHOT',
  INCREMENT_KILLS: 'INCREMENT_KILLS',
  SET_SELECTED_TOWER: 'SET_SELECTED_TOWER',
  SET_GAME_OVER: 'SET_GAME_OVER',
  SET_VICTORY: 'SET_VICTORY',
  RESET_SPAWN_TIMER: 'RESET_SPAWN_TIMER',
  SET_SHOTS: 'SET_SHOTS',
  SET_SPAWN_TIMER: 'SET_SPAWN_TIMER',
  SET_ENEMIES_SPAWNED: 'SET_ENEMIES_SPAWNED'
}

export const ACTIONS = {
  INIT_GAME: 'initGame',
  LOAD_LEVEL: 'loadLevel',
  RESTART_LEVEL: 'restartLevel',
  NEXT_LEVEL: 'nextLevel',
  SPAWN_ALLY: 'spawnAlly',
  UPGRADE_TOWER: 'upgradeTower',
  SELECT_TOWER_POSITION: 'selectTowerPosition',
  UPDATE_GAME: 'updateGame',
  HANDLE_GAME_CLICK: 'handleGameClick',
  SET_PLACE_MODE: 'setPlaceMode'
}

export const GETTERS = {
  GET_SELECTED_TOWER: 'selectedTower',
  GET_UPGRADE_COST: 'upgradeCost',
  GET_PATH_POINTS: 'pathPoints',
  GET_REVERSE_PATH_POINTS: 'reversePathPoints',
  GET_LEVELS: 'levels',
  GET_CURRENT_LEVEL_ID: 'currentLevelId',
  GET_CURRENT_PATH: 'currentPath',
  GET_MAX_ENEMIES: 'maxEnemies',
  GET_ENEMIES_SPAWNED: 'enemiesSpawned',
  GET_TOWER_POSITIONS: 'towerPositions',
  GET_TOWERS: 'towers',
  GET_ENEMIES: 'enemies',
  GET_ALLIES: 'allies',
  GET_BARRICADES: 'barricades',
  GET_ARTILLERY_STRIKES: 'artilleryStrikes',
  GET_ALL_SHOTS: 'allShots',
  GET_POINTS: 'points',
  GET_TOTAL_KILLS: 'totalKills',
  GET_SELECTED_TOWER_ID: 'selectedTowerId',
  GET_GAME_OVER: 'gameOver',
  GET_VICTORY: 'victory',
  GET_PLACE_MODE: 'placeMode',
  GET_SHOW_INSUFFICIENT_FUNDS: 'showInsufficientFunds',
  GET_SPAWN_TIMER: 'spawnTimer',
  GET_CURRENT_LEVEL: 'currentLevel',
  GET_SHOOTER_ENEMIES: 'shooterEnemies'
}