export const MISSIONS = [
  {
    id: 'river-01',
    order: 1,
    name: 'Уровень 1',
    difficulty: 'Базовый',
    startBudget: 240,
    waveInterval: 1450,
    route: [
      { x: 2, y: 53 },
      { x: 26, y: 53 },
      { x: 26, y: 28 },
      { x: 60, y: 28 },
      { x: 60, y: 66 },
      { x: 98, y: 66 },
    ],
    pads: [
      { id: 'a1', x: 11, y: 41 },
      { id: 'a2', x: 18, y: 25 },
      { id: 'a3', x: 40, y: 16 },
      { id: 'a4', x: 52, y: 49 },
      { id: 'a5', x: 71, y: 54 },
      { id: 'a6', x: 86, y: 76 },
    ],
    barrierSlots: [
      { id: 'w1', x: 18, y: 53, width: 6, angle: 90 },
      { id: 'w2', x: 60, y: 47, width: 6, angle: 0 },
    ],
    waveOrder: [
      'runner',
      'runner',
      'raider',
      'runner',
      'gunner',
      'raider',
      'runner',
      'gunner',
      'bulwark',
      'raider',
      'gunner',
      'bulwark',
    ],
  },
  {
    id: 'quarry-02',
    order: 2,
    name: 'Уровень 2',
    difficulty: 'Средний',
    startBudget: 330,
    waveInterval: 1280,
    route: [
      { x: 2, y: 20 },
      { x: 32, y: 20 },
      { x: 32, y: 70 },
      { x: 53, y: 70 },
      { x: 53, y: 38 },
      { x: 82, y: 38 },
      { x: 82, y: 82 },
      { x: 98, y: 82 },
    ],
    pads: [
      { id: 'b1', x: 12, y: 31 },
      { id: 'b2', x: 26, y: 58 },
      { id: 'b3', x: 42, y: 58 },
      { id: 'b4', x: 46, y: 27 },
      { id: 'b5', x: 67, y: 50 },
      { id: 'b6', x: 73, y: 70 },
      { id: 'b7', x: 91, y: 69 },
    ],
    barrierSlots: [
      { id: 'q1', x: 32, y: 44, width: 6, angle: 0 },
      { id: 'q2', x: 67, y: 38, width: 6, angle: 90 },
      { id: 'q3', x: 82, y: 60, width: 6, angle: 0 },
    ],
    waveOrder: [
      'runner',
      'runner',
      'gunner',
      'raider',
      'gunner',
      'bulwark',
      'runner',
      'officer',
      'raider',
      'gunner',
      'bulwark',
      'officer',
      'bulwark',
    ],
  },
  {
    id: 'terminal-03',
    order: 3,
    name: 'Уровень 3',
    difficulty: 'Сложный',
    startBudget: 430,
    waveInterval: 1120,
    route: [
      { x: 2, y: 74 },
      { x: 20, y: 74 },
      { x: 20, y: 22 },
      { x: 48, y: 22 },
      { x: 48, y: 82 },
      { x: 70, y: 82 },
      { x: 70, y: 36 },
      { x: 98, y: 36 },
    ],
    pads: [
      { id: 'c1', x: 10, y: 61 },
      { id: 'c2', x: 28, y: 34 },
      { id: 'c3', x: 40, y: 69 },
      { id: 'c4', x: 57, y: 34 },
      { id: 'c5', x: 58, y: 70 },
      { id: 'c6', x: 78, y: 50 },
      { id: 'c7', x: 87, y: 48 },
    ],
    barrierSlots: [
      { id: 't1', x: 20, y: 48, width: 6, angle: 0 },
      { id: 't2', x: 59, y: 82, width: 6, angle: 90 },
      { id: 't3', x: 84, y: 36, width: 6, angle: 90 },
    ],
    waveOrder: [
      'runner',
      'gunner',
      'raider',
      'gunner',
      'officer',
      'bulwark',
      'raider',
      'officer',
      'bulwark',
      'gunner',
      'bulwark',
      'officer',
      'bulwark',
      'officer',
    ],
  },
]
