FROM nginx:1.29-alpine

RUN apk add --no-cache openssl

WORKDIR /opt/app

COPY dist/ /usr/share/nginx/html/
COPY package.json /opt/app/package.json
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/entrypoint.sh /usr/local/bin/nginx-entrypoint.sh

RUN chmod +x /usr/local/bin/nginx-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/nginx-entrypoint.sh"]
